#!/bin/bash
env
export JENKINS_HOST=$JENKINS_PORT_8080_TCP_ADDR
export JENKINS_PORT=$JENKINS_PORT_8080_TCP_PORT
curl -O http://$JENKINS_HOST:$JENKINS_PORT/jnlpJars/slave.jar
java -jar slave.jar \
      -jnlpUrl http://$JENKINS_HOST:$JENKINS_PORT/computer/$SLAVE_NAME/slave-agent.jnlp
